name: Snyk Full Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-full-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Snyk CLI + SARIF converter
        run: npm install -g snyk snyk-to-sarif

      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN

      # --------------------
      # Open Source Dependencies Scan
      # --------------------
      - name: Snyk OS Scan
        run: snyk test --all-projects --json-file-output=snyk-os.json || true

      - name: Validate OS JSON
        run: |
          if [ ! -s snyk-os.json ]; then
            echo "{}" > snyk-os.json
          fi
          cat snyk-os.json

      - name: Convert OS Scan to SARIF
        run: snyk-to-sarif snyk-os.json > snyk-os.sarif

      - name: Upload OS SARIF to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-os.sarif

      - name: Monitor OS Dependencies in Snyk
        run: snyk monitor --all-projects || true

      # --------------------
      # Snyk Code (SAST) Scan
      # --------------------
      - name: Snyk Code Scan
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Validate Code SARIF
        run: |
          if [ ! -s snyk-code.sarif ]; then
            echo '{"version":"2.1.0","runs":[]}' > snyk-code.sarif
          fi

      - name: Upload Snyk Code SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Monitor Code in Snyk
        run: snyk code monitor || true
