name: Snyk Full Security Scan

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-full-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # --------------------
      # Checkout repository
      # --------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------
      # Setup Node.js
      # --------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # --------------------
      # Install Snyk CLI
      # --------------------
      - name: Install Snyk CLI
        run: npm install -g snyk

      # --------------------
      # Authenticate Snyk
      # --------------------
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN

      # --------------------
      # Snyk Scan for all projects (Open Source Dependencies)
      # --------------------
      - name: Run Snyk test for all projects (SARIF)
        run: snyk test --all-projects --sarif-file-output=snyk-all.sarif || true

      # --------------------
      # Upload SARIF to GitHub Security
      # --------------------
      - name: Upload Snyk SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-all.sarif

      # --------------------
      # Monitor all projects in Snyk
      # --------------------
      - name: Monitor all projects in Snyk
        run: snyk monitor --all-projects || true

      # --------------------
      # Snyk Code Scan (SAST)
      # --------------------
      - name: Snyk Code Scan
        run: snyk code test --sarif-file-output=snyk-code.sarif || true

      - name: Upload Snyk Code SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Monitor Snyk Code
        run: snyk code monitor || true
