name: Snyk Full Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-full-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # --------------------
      # Checkout repository
      # --------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------
      # Setup Node.js
      # --------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # --------------------
      # Install Snyk CLI + SARIF converter + jq
      # --------------------
      - name: Install Snyk CLI + SARIF converter + jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install -g snyk snyk-to-sarif

      # --------------------
      # Authenticate Snyk
      # --------------------
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN

      # --------------------
      # Snyk Scan for All Projects (Open Source Dependencies)
      # --------------------
      - name: Run Snyk test for all projects
        run: snyk test --all-projects --json-file-output=snyk-os.json || true

      - name: Split Snyk JSON array into individual project files
        run: |
          mkdir -p snyk-json
          if [ -s snyk-os.json ]; then
            # Split array elements into individual files
            jq -c '.[]' snyk-os.json | nl -w1 -s: | while IFS=: read i obj; do
              echo $obj | jq '.' > snyk-json/project-$i.json
            done
          else
            echo "snyk-os.json is empty, skipping JSON split."
          fi
      
      - name: Convert each project JSON to SARIF
        run: |
          mkdir -p snyk-sarif
          for file in snyk-json/*.json; do
            if [ -s "$file" ]; then
              npx snyk-to-sarif "$file" > "snyk-sarif/$(basename $file .json).sarif"
            fi
          done


      - name: Upload all OS SARIF files
        run: |
          for sarif in snyk-sarif/*.sarif; do
            gh codeql upload-sarif "$sarif" || true
          done

      - name: Monitor all OS projects in Snyk
        run: snyk monitor --all-projects || true

      # --------------------
      # Snyk Code Scan (SAST)
      # --------------------
      - name: Snyk Code Scan
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Ensure Code SARIF is valid
        run: |
          if [ ! -s snyk-code.sarif ]; then
            echo '{"version":"2.1.0","runs":[]}' > snyk-code.sarif
          fi

      - name: Upload Code SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Monitor Code in Snyk
        run: snyk code monitor || true
