name: Snyk Full Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-full-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # --------------------
      # Checkout repository
      # --------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------
      # Setup Node.js
      # --------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # --------------------
      # Install Snyk CLI + SARIF converter
      # --------------------
      - name: Install Snyk CLI + SARIF converter
        run: npm install -g snyk snyk-to-sarif

      # --------------------
      # Authenticate Snyk
      # --------------------
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN

      # --------------------
      # Open Source Dependencies Scan (SCA)
      # --------------------
      - name: Snyk Scan for pom.xml
        run: |
          if [ -f pom.xml ]; then
            echo "Scanning pom.xml..."
            snyk test --file=pom.xml --json > snyk-pom.json || true
            snyk-to-sarif snyk-pom.json > snyk-pom.sarif
            cat snyk-pom.sarif
            snyk monitor --file=pom.xml || true
          else
            echo "pom.xml not found, skipping."
          fi

      - name: Upload pom.xml SARIF
        run: |
          if [ -f snyk-pom.sarif ]; then
            gh codeql upload-sarif snyk-pom.sarif || true
          else
            echo "pom.sarif not found, skipping upload."
          fi

      - name: Snyk Scan for package.json
        run: |
          if [ -f package.json ]; then
            echo "Scanning package.json..."
            snyk test --file=package.json --json > snyk-npm.json || true
            snyk-to-sarif snyk-npm.json > snyk-npm.sarif
            cat snyk-npm.sarif
            snyk monitor --file=package.json || true
          else
            echo "package.json not found, skipping."
          fi

      - name: Upload package.json SARIF
        run: |
          if [ -f snyk-npm.sarif ]; then
            gh codeql upload-sarif snyk-npm.sarif || true
          else
            echo "npm SARIF not found, skipping upload."
          fi

      # --------------------
      # Snyk Code Scan (SAST)
      # --------------------
      - name: Snyk Code Scan
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Ensure Code SARIF is valid
        run: |
          if [ ! -s snyk-code.sarif ]; then
            echo '{"version":"2.1.0","runs":[]}' > snyk-code.sarif
          fi
          cat snyk-code.sarif

      - name: Upload Code SARIF to GitHub Security
        run: |
          if [ -f snyk-code.sarif ]; then
            gh codeql upload-sarif snyk-code.sarif || true
          else
            echo "Code SARIF not found, skipping upload."
          fi

      - name: Monitor Code in Snyk
        run: snyk code monitor || true
